# Bu yaml içerisinde pod seviyesinde oluşan kullanıcı bizim belirlediğimiz ve root olmayan bir kullanıcı olur.
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper
  namespace: default
spec:
  containers:
  - command:
    - sleep
    - "4800"
    image: ubuntu
    imagePullPolicy: Always
    name: ubuntu
    securityContext:
      runAsUser: 1010