apiVersion: v1
kind: Pod
metadata:
  name: health-check-pod
spec:
  containers:
  - name: health-check
    image: busybox:latest
    command: ["sh", "-c"]
    args: ["nc -z localhost 80 && exit 0 || exit 1"]
    livenessProbe:
      exec:
        command: ["sh", "-c"]
        args: ["nc -z localhost 80 && exit 0 || exit 1"]
      initialDelaySeconds: 15
      periodSeconds: 20
      failureThreshold: 3
  restartPolicy: Always