# Bu yaml içerisinde bir uygulama podunun içerisinde özel olarak hazırladığımız servis hesabının eklenme yönetimini görebilirsiniz.
apiVersion: v1
kind: Pod
metadata:
  name: mykubernetesapp
  labels:
    type: application
spec:
  containers:
    - name: mykubernetesapp
      image: mykubernetesapp-image
  serviceAccountName: mykubernetesapp-sa 