apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-check
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-check
  template:
    metadata:
      labels:
        app: health-check
    spec:
      containers:
      - name: health-check
        image: busybox:latest
        command: ["sh", "-c"]
        args: ["nc -z localhost 80 && exit 0 || exit 1"]
        readinessProbe:
          exec:
            command: ["sh", "-c"]
            args: ["nc -z localhost 80 && exit 0 || exit 1"]
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 3